Icon button
Kvitkovo/online_store pull request #33
Opened 2023-08-21 10:27 UTC by Svitlana-G

2023-08-21 13:42 UTC, FortizFil requested changes

2023-08-21 13:42 UTC, FortizFil commented on frontend/src/pages/Home.js
> +import * as React from 'react';
What is it for?

2023-08-22 13:59 UTC, Svitlana-G commented on frontend/src/components/ui-kit/components/IconButton/IconButton.jsx
> +    <img
Changed to button

2023-08-22 14:37 UTC, FortizFil requested changes

2023-08-22 14:37 UTC, FortizFil commented on frontend/src/components/ui-kit/components/IconButton/IconButton.module.scss
> +    cursor: pointer;
Remove this

2023-08-22 14:37 UTC, FortizFil commented on frontend/src/components/ui-kit/components/IconButton/IconButton.jsx
> +  const addClassname = () => {
Looks good, but optimize this

2023-08-24 10:11 UTC, FortizFil approved these changes
Looks good

2023-08-24 10:53 UTC, merged