initial styling
Kvitkovo/online_store pull request #52
Opened 2023-09-12 09:31 UTC by annaBalabak

2023-09-19 08:11 UTC, FortizFil requested changes

2023-09-19 08:11 UTC, FortizFil commented on frontend/src/components/common/Header/BurgerMenu/BurgerMenu.jsx
> +  return (
We break a lot of code into components

2023-09-19 08:11 UTC, FortizFil commented on frontend/src/components/common/Header/BurgerMenu/BurgerMenu.module.scss
> +  padding: 8px 16px 16px 16px;
You can simply write `padding: 8px 16px 16px;`

2023-09-19 08:11 UTC, FortizFil commented on frontend/src/components/common/Header/BurgerMenu/BurgerMenu.module.scss
> +  padding: 8px 8px 0px 8px;
You can simply write `padding: 8px 8px 0;`

2023-09-19 08:11 UTC, FortizFil commented on frontend/src/components/common/Header/BurgerMenu/BurgerMenu.module.scss
> +  background-color: #fff;
Use colors from the variables

2023-09-19 08:11 UTC, FortizFil commented on frontend/src/components/common/Header/BurgerMenu/BurgerMenu.module.scss
> +  list-style: none;
padding and list-style are already set globally, remove it

2023-09-19 08:11 UTC, FortizFil commented on frontend/src/components/common/Header/Header/Header.jsx
> +              <Button
You don't need a button here

2023-09-19 08:11 UTC, FortizFil commented on frontend/src/components/common/Header/Header/Header.jsx
> +              <NavLink
Make it an array of objects and output it through map, it will be much less code

2023-09-19 08:11 UTC, FortizFil commented on frontend/src/components/common/Header/Header/Header.jsx
> +              <ICONS.person />
This should be the iconButton

2023-09-19 08:11 UTC, FortizFil commented on frontend/src/components/common/Header/Header/Header.module.scss
> +header {
No need to register all classes in the parent component

2023-09-19 08:11 UTC, FortizFil commented on frontend/src/components/common/Header/Header/Header.module.scss
> +    padding: 0;
padding and list-style are already set globally, remove it

2023-09-19 08:11 UTC, FortizFil commented on frontend/src/components/common/Header/Header/Header.module.scss
> +    text-decoration: none;
text-decoration is already set globally, remove it

2023-09-19 08:11 UTC, FortizFil commented on frontend/src/components/common/Header/BurgerMenu/BurgerMenu.module.scss
> +  text-decoration: none;
text-decoration is already set globally, remove it

2023-09-19 08:11 UTC, FortizFil commented on frontend/src/components/common/Header/Header/Header.module.scss
> +    cursor: pointer;
Doesn't NavLink give us this property?

2023-09-19 08:11 UTC, FortizFil commented on frontend/src/components/common/Header/Header/Header.module.scss
> +      margin: 0 0px 0 174px;
0px => 0

2023-09-19 08:53 UTC, annaBalabak commented on frontend/src/components/common/Header/Header/Header.jsx
> +            <button className={styles.btnLanguage}>Укр</button>
They want to keep it for the future in case we decide to add any other language

2023-09-20 07:28 UTC, FortizFil requested changes

2023-09-20 07:28 UTC, FortizFil commented on frontend/src/components/Layouts/Header/BurgerMenu/BurgerMenu.jsx
> +  const toggleMenu = () => {
Add useCallback, and do it through prevState

2023-09-20 07:28 UTC, FortizFil commented on frontend/src/components/Layouts/Header/NavigationMenu/NavigationMenu.jsx
> +  const navClassName =
add useMemo

2023-09-20 07:28 UTC, FortizFil commented on frontend/src/components/Layouts/Header/BurgerMenu/BurgerMenu.jsx
> +        <OpenMenu toggleMenu={toggleMenu} />
The menu should be full screen height

2023-09-20 07:28 UTC, FortizFil commented on frontend/src/components/Layouts/Header/BurgerMenu/OpenMenu.jsx
> +  const closeNavigation = () => {
What is it for?

2023-09-20 07:28 UTC, FortizFil commented on frontend/src/components/Layouts/Header/BurgerMenu/BurgerMenu.jsx
> +/* import { NavLink } from 'react-router-dom';
Delete all comments

2023-09-20 07:28 UTC, FortizFil commented on frontend/src/components/Layouts/Header/BurgerMenu/ClosedMenu.jsx
> +        <div className={styles.burgerIcon} onClick={toggleMenu}>
This should be iconButton

2023-09-20 07:28 UTC, FortizFil commented on frontend/src/components/Layouts/Header/BurgerMenu/OpenMenu.jsx
> +          <ICONS.closeMobile onClick={closeNavigation} />
This should be iconButton

2023-09-20 07:28 UTC, FortizFil commented on frontend/src/components/Layouts/Header/BurgerMenu/OpenMenu.jsx
> +        <p className={`${styles.links} ${styles.catalogue}`}>
Why is it a button on a desktop and a text on a mobile?

2023-09-20 07:28 UTC, FortizFil commented on frontend/src/components/Layouts/Header/NavigationMenu/NavigationMenu.jsx
> +        <li key={index}>
Don't use index, you have label and to unique values, it's better to take one of them

2023-09-20 07:28 UTC, FortizFil commented on frontend/src/components/Layouts/Header/NavigationMenu/NavigationMenu.jsx
> +              item.label === 'Акції' ? styles.promotions : ''
Promotions always go first, maybe it's better to do it through css?

2023-09-20 07:28 UTC, FortizFil commented on frontend/src/components/Layouts/Header/BurgerMenu/OpenMenu.jsx
> +            <IconButton icon={<ICONS.phone />} className={styles.phoneIcon} />
It's better to just use the icon here

2023-09-20 07:28 UTC, FortizFil commented on frontend/src/components/Layouts/Header/Header/Header.jsx
> +  window.onscroll = () => {
It's probably better to useEffect here

2023-09-20 07:28 UTC, FortizFil commented on frontend/src/components/Layouts/Header/Header/Header.jsx
> +          <li className={styles.accessIcon}>
Where is ul?

2023-09-21 07:07 UTC, FortizFil requested changes

2023-09-21 07:07 UTC, FortizFil commented on frontend/src/components/Layouts/Header/Header.jsx
> +  useEffect(() => {
Without an array of dependencies, useEffect makes no sense, it should not be triggered for every user action

2023-09-21 07:07 UTC, FortizFil commented on frontend/src/components/Layouts/Header/Components/BurgerMenu/OpenMenu.jsx
> +        <IconButton icon={<ICONS.closeMobile />} onClick={toggleMenu} />
Put it behind NavLink, because when I close the menu I am taken to the main page

2023-09-21 07:07 UTC, FortizFil commented on frontend/src/components/Layouts/Header/Components/BurgerMenu/BurgerMenu.module.scss
> +.openMenu {
It has no position, when I open the menu, it should be on top of the content, not push it down. Add position:fixed

2023-09-21 07:22 UTC, FortizFil requested changes

2023-09-21 07:22 UTC, FortizFil commented on frontend/src/components/Layouts/Header/Header.module.scss
> +  margin: 7px 0;
This is padding

2023-09-21 12:40 UTC, FortizFil approved these changes

2023-09-21 12:57 UTC, merged